

#cipherText = 'QHDLXNQLYNGAIGWBCERJFEARNIBKXUSVGZXKYNPXXTKGAATZRQCRFYIDCCLYXHUQXEIXFAFGEAMMAL\
#YRGAYXQMTGACDJSYRTLEXUVRVIYFFEGXFKOYSPHGBBYTRESOXUNTXXAKLUAWYDINAAWCZWIFVMCROI \
#UCEIFJYDJAYZJBEOTMUSGAGAYYQNIPTFPYMCBOYDYYSVGWDOJTBZLMFBYJXLQCUDRRIGMIUYWMQUUF \
#RPCZQHTVJOUJSMNRVQQZEJYLACNHRFCPTFENZYEJCLYMBQUCGUMYQDBUAWLQTMOAXCZJBEABHQJYEA \
#MQQDNIRLNTUINRMCYUJAQTZQMGOEXUDEONQPIDBXWNKNIEUNQMBQDUFGXLFXYBVKNTEZCBFJGJUTVH \
#HMBWOZIFQNCTLMBQELYVGNTUHIAXNQUHSROYZJCEFUIACVOBFVAEGBBHGNEIMOHIYRIOZQ'


cipherText = 'LNKNWQXCKEWAZHVJWAEORNLUPSSAITOEROVNWUIWTVVTZSIFPUTDAGUUTGE \
VWHTAZGDIEBIPWSZJBUHDZOBELBLPQBQOWPPRLNYWJVWAEPABISFQBUDMVN \
QPDAEZQAWHVCMBOOXEKNORVHIGLOEOWSWHVLZRVEEPBBWHVLIFWIEDIOLTR \
JBFRFKDIGFOEPQAHNKPPRVEWWKGVSVAURGTFIMGRTYNWJVODATVJHKKVGKE \
FNQTLNFBACHCZAAGKAKIGFWEIUWSPYJPMELEJWAVWHROJRHNTWTYHDSUWAH \
OWKCEJRVWBRVTGDQYRSFLPRUSFJULUEKQZAKODAQGRCTQZEHDKKURLNKDIG \
VODABULNXIQTKTGAZUDPJXMZDDVKCGRNKDQFTUVOBVRNSUXNWIVJBYBATYC \
ZXLRPQAJAEZZRILVYBVQGFJIYOSFNBFRFWWKGVWYEKUFOLHLCRSJEJYBHRR \
MNQYSAIELNXKVVWAWPMEIIMAGRDRJSWENIRHTBZEUIGFHLWPWFSETQTNWEF \
JBUHSLXRRFTRJLQUENQXFRMVOPBUTEKBRVTYAARLEEHIEJEUEVVQTFWAXHT \
TDWSWHVYWAFLLOQBQSNDQPKTYAVFHEDALGRMVLZBEASHMSUODPPNWPVNQBG \
TFPPRSRVOMAWDRUQUDVVOBRDDZHGCXRJQMQWHVOIZHOSFMPWIYKXRWHRPQZ \
DYSAMKFUJALSRRVJBRUIECWAWHVOMCHRJKVNODVPIVOSROQTLVVPPRPTFOP \
BZTYWBVKAMAVBWBVAVUDSKUQAFODEVTWORZMPLSZKVZBWFNSVVNFSVRDRCU \
NVQIJDMQEUKWAVWWZHTGDKVIMGZOFNBUUEVIWEHYVWZFWOTKUCOEKAQGDNU \
WAZBHVWTGKIJBIEIRFIAGUOECQUDVVXMRQUICMQWOGQJYLSYPPVVASOBEDC \
KEPNYEDKZRHSGAKVDLCUJRHNZJLHFEUPWQRTYEANVMISIYOATAEURIJJWJV \
TLZGVQGKDMADTLNIYKIJPWEBOWPPRPACWGNUCYEXROAXKPNVAINQIHDRPIY \
POJPMKDCKHGGKEJWURJEEAZNOCFJKYXSZKVFWHRPQUDVVKVGKEFNQTLNFBA \
CHCZAAYDSKUMNUHVOMAWTFIMNPEDKQERNKDQFVUSFMPWWZPPNUEHQMFWTYW \
BVZOLHLSRRNWZQLTKKAVUCYWZYHSCUMYOWYKARQTZPBBWHVHQAQERJABFIV \
PGNQDZPQFSUSHQFKEUEVGKEKDQEGVFHCZHOWPPRMOLNVNOOWPPNWSFYQRWY \
JEZPOYVHTNQDUNPBRKVNEURBFPPXQENKNZBWFNSGKECWBGHRYWDVQGIAIQP \
YJGMGFHFBPBQOLNMQPESUBULNBEVTLTRZDVVASHMGRPLXTVVHNEBUPRNWTY \
DCVOMKFECHMAWMVIWVUSFIMOUIVBMKWRRYBFIRFIULPAEQAPUIGPAGKIJWJ \
FWRRYBJKITDQARWGQJYLSYICFWNVYMFVAIETLEEZIXRUFVYBVFAEJWGKEIA \
OVYEIANRUEEYMFDNUWCGKOIEBVHSWKZZBSVRMEDLJPIGHMVJBFDNUEUHVTK \
NCFWTFPPRUERZMEUEGKAVQGJKURFOEBQQHNTAQAPYRYKHUATUVBGOLXBRUR \
FNAJLLCDIIHCIAXGLNKDWHJHZDWCHIYWDRDLNWGFEEVJKNXTZKCFLNKNCFW \
IECBBJOFZIHWHFNQGLEJWTBQEZYIAKEIAOVYEFJTLWHVCMAHRRHKBQCCQAV \
RNJWBJKITDQUDVVWZELVVZEVWHRBMJIATPAVQICHCFWRRPQBQBLPEULCYEP \
BSEZJUBVTTWARVWZHTFXFWEKRQOFJMPDNWAMYPOIAARQSZXTRWHRJQQROWP \
PRQETAAFLTPKNUHRVWNGHRGQJYLSYEVTLNUABNLLRHTGKEWWKGVWZPPEHFV \
NMAFEJKVJKITDULFOEYTHVIFJAUDVVXMRQGIKCAGEUWVQLHFLMVQAWQBHUE \
NKZXWOUKBULSWKZVDMNATYDWRNMGKAKOKNUCVHGNVIECTRSOZJBVVDZOKHV \
SVZQAWHZODBOUDAWAZHZYPSDCKOKNQNFPJRDDUQKRGOWPMADPGWZRQTCUTR \
DDZJOGRCFJKYXSZKVFGIIAKGOYFLXBVIKABBWHFOMNWWYEKULHRRMNURZRM \
QDFREZEHSLHBPDNSAWOWAZJMQRNCUJLIUCHGFWAKEVTDNUXIYDNTEVTWHVB \
IPWSRJLNUGLIMAWSFJJBWHJELRVOWAIPKQLAAGLOEWVQWHZOKNQNFPXBVSZ \
XTLEEYAZRGOEA'


for shift in range(1,19,1):
    coincidenceCount = 0
    for index in range(0,(len(cipherText))-1):
        shiftedIndex = (index + shift) % (len(cipherText))
        if(cipherText[index] == cipherText[shiftedIndex]):
           coincidenceCount +=1;

    print ('Shift:', shift, 'Coincidence:', coincidenceCount)
        

#part 8
    
print('AND YET EVEN THOUGH CRYPTOGRAPHY HAS INFLUENCED HUMAN AFFAIRS FOR MILLENIA DEVELOPMENTS OVER \
      THE LAST THIRTY YEARS HAVE COMPLETELY YES COMPLETELY CHANGED OUR UNDERSTANDING OF IT IF YOU \
      PLOTTED WHEN THE BASIC MATHEMATICAL DISCOVERIES IN CRYPTOGRAPHY WERE MADE YOU WOULD SEE \
      A FEW IN ANTIQUITY MAYBE A FEW FROM THE MIDDLE AGES TILL THE EIGHTEEN HUNDREDS ONE IN THE NINETEEN \
     TWENTIES THE ONE TIME PAD A FEW MORE AROUND WORLD WAR TWO AND THEN AFTER THE BIRTH OF COMPUTATIONAL \
      COMPLEXITY THEORY IN THE NINETEEN SEVENTIES BOOM BOOM BOOM BOOM BOOM BOOM BOOMX ')

